spring.application.name=gateway
spring.jackson.time-zone=Asia/Bangkok

jwt.secret=X32ggLsxyb6Q0eE27VfMTo84J2CeKEbNLdW1OQItfFU=

# API Gateway Routes
spring.cloud.gateway.routes[0].id=authentication-service
spring.cloud.gateway.routes[0].uri=lb://authentication
spring.cloud.gateway.routes[0].predicates[0]=Path=/authentication/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.routes[1].id=operation-service
spring.cloud.gateway.routes[1].uri=lb://operation
spring.cloud.gateway.routes[1].predicates[0]=Path=/operation/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

spring.cloud.gateway.routes[2].id=report-service
spring.cloud.gateway.routes[2].uri=lb://report
spring.cloud.gateway.routes[2].predicates[0]=Path=/report/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter

# Service Discovery
#spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Server Port
server.port=8765