spring.application.name=operation
server.port=9998

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.banner.location=banner.txt
spring.jpa.open-in-view=false

# MS SQL Connectivity
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ShopyMenu;encrypt=true;trustServerCertificate=true;
spring.datasource.username=ShopyAdmin
spring.datasource.password=My@Dm!n123

management.endpoints.web.exposure.include=health,info

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR