spring.application.name=api-registry
spring.banner.location=banner.txt
spring.application.title=my api registry application
sprig.application.version=1.0.0.1
server.port=8761

eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
